### ISSUE TITLE
calibraion failed when no motor connected to axis0

### ISSUE THREAD

**Issue by taskx6004** [taskx6004/fusioneye#1]
file: odrive_interface.py
line: 134

FIXME
[ERROR] [1547651563.496689]: Failed calibration with axis error 0x40, motor error 0x1
could not pass axis0 calibraion even --calibrate_axis=2 was set

TODO
add on_startup_calibration parameter for each axis

**Comment by zarathustr** [comment]
Please first make sure **'[ERROR] [1547651563.496689]: Failed calibration with axis error 0x40, motor error 0x1 could not pass axis0 calibraion even --calibrate_axis=2 was set'** won't happen after reposer the ESC and reconnect the USB wire. If this error repeats, contact me again, since I have encountered this error before but get passed simply after one reboot.

**Comment by taskx6004** [comment]
Tested it works, after PR#4. Thanks.
